databases:
  - name: spiceai-db
    plan: free
    databaseName: spiceai_admin
    user: spiceai

services:
  - type: web
    name: spiceai-admin
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    envVars:
      - key: APP_NAME
        value: SpiceAI_Admin
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:wNJGsaAmCU/i2VVp/8s8xlh69cbap6jCNHaMgQNv7M4=
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: spiceai-db
          property: connectionString
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
